# Numpy Function

NumPy is a general-purpose array processing package. It provides high-performance multidimensional array object, and tools for working with these arrays. It is a fundamental package for scientific computing with Python. 

### What is an array? 

An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in Python can only contain values corresponding to same data type. 

In [4]:
# pip install numpy - In case you have installed python manually
# conda install numpy - In case you have installed conda environment

In [2]:
# Importing Numpy library

import numpy as np 

In [5]:
# Converting list into array

my_lst = [1,2,3,4,5]

arr = np.array(my_lst)

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr

array([1, 2, 3, 4, 5])

In [8]:
arr.shape

(5,)

In [22]:
## Multinested array

my_lst1 = [1,2,3,4,5]
my_lst2 = [2,3,4,5,6]
my_lst3 = [9,7,6,8,9]

arr = np.array([my_lst1, my_lst2,my_lst3])

In [23]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [18]:
arr.shape

(3, 5)

In [19]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

# Indexing

In [20]:
## Accesing the array element

arr = np.array([1,2,3,4,5,6,7,8,9])

In [21]:
arr[3]

4

In [24]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [25]:
arr[1:,3:]

array([[5, 6],
       [8, 9]])

In [26]:
arr[1:,2:4]

array([[4, 5],
       [6, 8]])

In [27]:
arr[1:2,1:4]

array([[3, 4, 5]])

In [29]:
arr = np.arange(0,10)

In [30]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr = np.arange(0,10, step = 2)

In [32]:
arr

array([0, 2, 4, 6, 8])

In [33]:
# To get n numbers of point between 2 values

np.linspace(1,100,250)

array([  1.        ,   1.39759036,   1.79518072,   2.19277108,
         2.59036145,   2.98795181,   3.38554217,   3.78313253,
         4.18072289,   4.57831325,   4.97590361,   5.37349398,
         5.77108434,   6.1686747 ,   6.56626506,   6.96385542,
         7.36144578,   7.75903614,   8.15662651,   8.55421687,
         8.95180723,   9.34939759,   9.74698795,  10.14457831,
        10.54216867,  10.93975904,  11.3373494 ,  11.73493976,
        12.13253012,  12.53012048,  12.92771084,  13.3253012 ,
        13.72289157,  14.12048193,  14.51807229,  14.91566265,
        15.31325301,  15.71084337,  16.10843373,  16.5060241 ,
        16.90361446,  17.30120482,  17.69879518,  18.09638554,
        18.4939759 ,  18.89156627,  19.28915663,  19.68674699,
        20.08433735,  20.48192771,  20.87951807,  21.27710843,
        21.6746988 ,  22.07228916,  22.46987952,  22.86746988,
        23.26506024,  23.6626506 ,  24.06024096,  24.45783133,
        24.85542169,  25.25301205,  25.65060241,  26.04

In [35]:
# Copy() Function and broadcasting

arr = np.array([1,2,3,4,5,6,7,8,9])

In [36]:
arr[3:] = 100

In [37]:
arr

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [38]:
arr1 = arr

In [39]:
arr1[3:] = 500
print(arr1)

[  1   2   3 500 500 500 500 500 500]


In [40]:
arr 

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

Since arr1 = arr, updating arr1 will also make changes in arr. In order to prevent such occurences, we will need to use copy function. 

In [41]:
arr1 = arr.copy()

In [42]:
print(arr)
arr1[3:] = 1000
print(arr1)

[  1   2   3 500 500 500 500 500 500]
[   1    2    3 1000 1000 1000 1000 1000 1000]


In [43]:
### Important conditions useful in Exploratory Data Analysis

In [44]:
val = 2

arr < 2

array([ True, False, False, False, False, False, False, False, False])

In [45]:
arr* 2

array([   2,    4,    6, 1000, 1000, 1000, 1000, 1000, 1000])

In [46]:
# To get an element

arr[arr<2]

array([1])

In [48]:
# To get number of ones in an array

np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [49]:
np.ones(7, dtype = int)

array([1, 1, 1, 1, 1, 1, 1])

In [50]:
# We cab also give 2D arrays as well

np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [51]:
# Random Distribution

np.random.rand(3,3)

array([[0.26608108, 0.27930697, 0.69867794],
       [0.44109547, 0.15300031, 0.60672385],
       [0.03719441, 0.4440942 , 0.19342681]])

In [52]:
arr_ex = np.random.rand(4,4)

In [53]:
arr_ex

array([[0.95804901, 0.71803988, 0.85965713, 0.16412752],
       [0.14319948, 0.05794038, 0.89928519, 0.50143319],
       [0.05860593, 0.37358109, 0.51158826, 0.38462407],
       [0.17681999, 0.35219493, 0.91483893, 0.49238556]])

In [56]:
np.random.randint(0,100,8).reshape(2,4)

array([[ 7, 67,  4, 63],
       [ 7, 61, 79,  3]])